### ISSUE TITLE
QA 654 FIXED

### ISSUE THREAD

**Issue by gitcoindev** [korrrba/test-ubiquibot#11]

**Comment by gitcoindev** [comment]
Okay, now what happened: the bounty was released back to pool because DISQUALIFY_TIME="2 minutes" was crossed and PR was linked afterwards. Now I will start again, reopen a PR within 2 minutes and use merge queue to merge, which caused the release before in #654. This should prove that bug is fixed.

**Comment by gitcoindev** [comment]
Looks good, wildcards not triggered, bug is fixed !

```
INFO (event): Creating adapters for supabase, telegram, twitter, etc...
    id: "1668cd5c-41b2-11ee-9ec5-a224e1b2b098"
INFO (event): Running pre handlers: nullHandler, event: push
    id: "1668cd5c-41b2-11ee-9ec5-a224e1b2b098"
INFO (event): Running main handlers: runOnPush, event: push
    id: "1668cd5c-41b2-11ee-9ec5-a224e1b2b098"
INFO (event): Running post handlers: nullHandler, event: push
    id: "1668cd5c-41b2-11ee-9ec5-a224e1b2b098"
INFO (http): POST / 200 - 831ms
```

**Comment by 0x4007** [comment]
Epic QA test with clear explanations, thank you @gitcoindev!
